### PR TITLE
#161255369 Add Search Functionality and Custom filtering based on parameters

### PR DESCRIPTION
**Pull request by 3N61N33R**
#### What does this PR do?
Adds search functionality and custom filtering base on parameters

#### Task to be completed
User should be able to search for articles by author, article title and tag/keyword or search by filtering.
Users would be able to filter articles by author, article title and tag/keywords, this would ensure a user only gets an article that matches ONLY the criteria that matches the criteria for the article they want.

Note:
If only author is supplied - the filter will only filter by author

If only tag is supplied - the filter will only filter by tag

if only keywords are supplied, the filter will only filter by keywords

If any of the above is supplied, the filter filters by the supplied filters

Scenario:
Any user (authenticated or not) should be able to search for articles on our platform .

#### Relevant PT stories
[Search_Filter 161255369](https://www.pivotaltracker.com/story/show/161255369)

#### Search
```Search by Title```
screen shot 2018-11-13 at 15 15 47

```Search by Tags```
screen shot 2018-11-13 at 15 15 22

```Search by Author```
screen shot 2018-11-13 at 15 14 23

#### Custom Filtering
```Filter by title```
screen shot 2018-11-13 at 15 05 53

```Filter by tag```
screen shot 2018-11-13 at 15 06 52

```Filter by author```
screen shot 2018-11-13 at 15 07 37

### CODE REVIEW

**Review by AnguleMathias — APPROVED** [review]
looks great!

**Comment by meshnesh** [comment]
Please include screenshots showing the various filter functions

**Review by maxwellgithinji — APPROVED** [review]
LGTM

**Review by Jwesh — APPROVED** [review]
lgtm

**Review by njeri-ngigi — APPROVED** [review]

**Review by njeri-ngigi — APPROVED** [review]

**Pull request merged**
