### PR TITLE
#161255348 Setup and deploy base application to Heroku

### PR DESCRIPTION
**Pull request by AnguleMathias**
#### What does this PR do?
* This PR sets up and deploys the application on Heroku to enable users to access it.

#### Description of Task to be completed?
* Enable users to access the live app using given urls
* App is deployed to staging for testing

#### How should this be manually tested?
* Application can be tested by using the following link:
`https://ah-codeofduty-staging.herokuapp.com`

#### What are the relevant pivotal tracker stories?
#161255348 - [Setup and deploy base application to Heroku](https://www.pivotaltracker.com/story/show/161255348)

### CODE REVIEW

**Review by Jwesh — COMMENTED** [review]
**add makemigrations to the release command**
like this:
```
release: python manage.py makemigrations;python manage.py migrate
```

**Review by Jwesh — APPROVED** [review]
lgtm

**Review by maxwellgithinji — APPROVED** [review]
LGTM

**Review by njeri-ngigi — APPROVED** [review]
lgtm

**Pull request merged**
