### PR TITLE
#161255350 - API Swagger Documentation

### PR DESCRIPTION
**Pull request by AnguleMathias**
#### What does this PR do?
* Swagger API Documentation of `Authors Haven - A Social platform for the creative at heart`

#### Description of Task to be completed?
* API Documentation for Authentiation Endpoints

#### How should this be manually tested?
* Click [here](https://ah-codeofduty-staging.herokuapp.com/) to test

#### Any background context you want to provide?
* Documentation offers a testing environment for User Signup and Login

#### What are the relevant pivotal tracker stories?
* #161255350 -[Document API using swagger](https://www.pivotaltracker.com/story/show/161255350)

#### Screenshots
screenshot 2018-10-29 at 09 14 46

### CODE REVIEW

**Review by Jwesh — COMMENTED** [review]
I see you have removed the tuple but will the test really pass with that change?

**Review by njeri-ngigi — APPROVED** [review]
lgtm

**Review by maxwellgithinji — APPROVED** [review]
LGTM

**Review by Jwesh — APPROVED** [review]
lgtm

**Pull request merged**
