### PR TITLE
Ch configure postgres 161255347

### PR DESCRIPTION
**Pull request by Jwesh**
#### What does this PR do?
* Upgrade django from `version 1.10` to `version 2.1`
* Integrate django project with postgres db.
* Updated django urls
* Added authentication class

#### Description of tasks to be completed
1. Install postgres
2. Create database
3. Create .env file and export the following:

* USER i.e database user
* DBNAME i.e name of the database you have created
* HOST use localhost or 127.0.0.1
* PASSWORD
* PORT i.e empty ' '

#### Any background context you want to provide?
Django 2.1 `urls.path()` allows a simpler, more readable URL routing syntax. 
For example, this example from previous Django 1.1:

`url(r'^articles/(?P<id>[0-9]{4})/$', views.articles)`

could be written as:

`path('articles/<int:id>/', views.articles)`

#### Screenshots
screen shot 2018-10-23 at 14 14 05

#### What are the relevant pivotal tracker stories?
* #161255347 - [Configure Authors Haven to use PostgreSQL as DB Engine](https://www.pivotaltracker.com/story/show/161255347)
* #161255342 - [Upgrade Authors Haven Django app from Django 1.10 to Django 2.1](https://www.pivotaltracker.com/story/show/161255342)

### CODE REVIEW

**Review by njeri-ngigi — COMMENTED** [review]
Please add more information to your PR description:
- instructions on how to set up Postgres locally
- and how to test this added functionality

**Review by 3N61N33R — APPROVED** [review]
lgtm

**Review by njeri-ngigi — COMMENTED** [review]
Also, if we need a .env file for this, could you add a .env.example file with dummy variables
e.g. [See example](https://github.com/njeri-ngigi/stackoverflow_api/blob/master/.env.example)

**Comment by maxwellgithinji** [comment]
In addition to @njeri-ngigi , Also include a link to the PT story in your pull request. Also use proper markdown format. find the link [here](https://guides.github.com/features/mastering-markdown/)

**Comment by AnguleMathias** [comment]
Looks good

**Review by maxwellgithinji — APPROVED** [review]
LGTM

**Review by AnguleMathias — APPROVED** [review]
Looks great

**Pull request merged**
