### PR TITLE
 #161255351 - Add JWT Authentication

### PR DESCRIPTION
**Pull request by maxwellgithinji**
#### What does this PR do?
* Add JWT authentication on login endpoint
#### Description of Task to be completed?
* Create a JWT authentication class
* Implement JWT in the login endpoint
#### How should this be manually tested?
1. Clone the repo and checkout `ft-jwt-auth-161255351` branch
2. setup the database
3. set up the virtual environment
4. Run the `/api/users/` endpoint with JSON data to register a user
5. Run the `/api/users/login` endpoint with the credentials you registered with
6. You should see a `token` as one of the responses

#### Any background context you want to provide?
* Implementation of JWT is more secure compared to hashing or using sessions to transfer or store 
 user data

#### What are the relevant pivotal tracker stories?
* Users should receive a JWT on successful Registration- [#161255351](https://www.pivotaltracker.com/story/show/161255351)

##### The login endpoint on Postman
screen shot 2018-10-30 at 02 41 41

### CODE REVIEW

**Review by AnguleMathias — CHANGES_REQUESTED** [review]
Work on coverage

**Review by AnguleMathias — APPROVED** [review]
looks great!

**Review by Jwesh — APPROVED** [review]
I feel like we could have a function that generates a token from an email

**Review by njeri-ngigi — CHANGES_REQUESTED** [review]
Remove redundant line in serializers.py line 104

**Review by njeri-ngigi — APPROVED** [review]

**Pull request merged**
