### PR TITLE
#161255340 Write unit tests for all functionality

### PR DESCRIPTION
**Pull request by 3N61N33R**
#### What does this PR do?
Has unit tests for existing functionality

#### Description of Task to be completed?
Write test for all functionality i.e signup and login

#### How should this be manually tested?
run ```python3 migrate.py test``` in terminal

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/161255340

### CODE REVIEW

**Review by AnguleMathias — APPROVED** [review]
lgtm

**Review by maxwellgithinji — CHANGES_REQUESTED** [review]
Add docstrings to all functions and modules

**Review by Jwesh — APPROVED** [review]
lgtm

**Review by kipropbrian — DISMISSED** [review]
The PR title format is wrong, the commit messages are also wrong kindly check the engineering playbook. You can also squash the commits into one.

**Review by maxwellgithinji — APPROVED** [review]

**Pull request merged**
